dataset_config = "E:\\train\\aiblender_v3\\flux_aiblender.toml"
vae_path = "I:\\train_models\\flux\\ae.sft"
t5_path = "I:\\train_models\\flux\\t5xxl_fp16.safetensors"
clip_model_path = "I:\\train_models\\flux\\clip_l.safetensors"
dit_weights_path = "I:\\train_models\\flux\\flux1-dev2pro.safetensors"
batch_size = "16"
max_train_epochs = "200"
learning_rate = "2e-4"
network_dim = "32"
gradient_accumulation_steps = "1"
timestep_sampling = "shift"
enable_low_vram = true
blocks_to_swap = "20"
output_dir = "./output"
output_name = "aiblender_flux_v3"
save_every_n_epochs = "1"
save_every_n_steps = "500"
use_network_weights = false
network_weights_path = "D:\\work\\project\\LoRAMaster\\LoRAMaster\\output\\wan2.2_jerry3d_t2v.safetensors"
generate_samples = true
sample_every_n_epochs = "1"
sample_every_n_steps = "100"
sample_prompt_text = "aiblender,"
custom_prompt_txt = false
custom_prompt_path = ""
num_cpu_threads_per_process = 1
num_processes = 1
lazy_loading = false
attention_implementation = "sdpa"
optimizer_type = "adamw8bit"
max_data_loader_n_workers = 2
auto_shutdown = true
log_type = "tensorboard"
log_prefix = ""
log_dir = "./logs"
log_tracker_name = ""
offload_inactive_dit = false
mixed_precision = "bf16"
discrete_flow_shift = "3.1582"
fp8 = true
cache_to_disk = true
