dataset_config = "E:\\train\\aiblender\\hunyuan_aiblender.toml"
vae_cache_cpu = false
skip_existing = true
vae_path = "I:\\train_models\\hunyuan\\vae.pt"
text_encoder_model_path = "I:\\train_models\\hunyuan\\llava_llama3_fp16.safetensors"
clip_model_path = "I:\\train_models\\hunyuan\\clip_l.safetensors"
dit_weights_path = "I:\\train_models\\hunyuan\\mp_rank_00_model_states.pt"
batch_size = "16"
max_train_epochs = "200"
learning_rate = "2e-4"
network_dim = "32"
gradient_accumulation_steps = "1"
timestep_sampling = "shift"
discrete_flow_shift = "5"
enable_low_vram = true
blocks_to_swap = "20"
output_dir = "./output"
output_name = "hunyuan_aiblender"
save_every_n_epochs = "10"
save_every_n_steps = "500"
use_network_weights = false
network_weights_path = "D:\\work\\project\\LoRAMaster\\LoRAMaster\\output\\wan2.2_jerry3d_t2v.safetensors"
generate_samples = true
sample_every_n_epochs = "1000"
sample_every_n_steps = "500"
sample_prompt_text = "Ultra HD 8K, aiblender,hyper-detailed 3D render of a cheerful character smiling warmly and waving both hands in a friendly greeting. The motion is fluid and energetic, with subtle motion blur emphasizing the dynamic gesture. Soft volumetric lighting illuminates the scene, creating a heartwarming atmosphere. The background features a beautifully blurred bokeh effect with golden sunlight, adding depth and cinematic quality. Rendered in Unreal Engine 5, Pixar-style animation, ultra-realistic textures, and vibrant colors. Trending on ArtStation, award-winning digital art, 16K resolution."
sample_image_path = "E:\\portables\\ComfyUI_Wan\\ComfyUI\\input\\pasted\\baozha_test.png"
sample_w = "512"
sample_h = "512"
sample_frames = "33"
sample_seed = "666666"
sample_steps = "10"
sample_at_first = false
custom_prompt_txt = false
custom_prompt_path = ""
fp8 = true
num_cpu_threads_per_process = 1
num_processes = 1
timestep_custom = true
min_timestep = "900"
timestep_boundary = "1000"
max_timestep = "1000"
lazy_loading = false
attention_implementation = "sdpa"
optimizer_type = "adamw8bit"
max_data_loader_n_workers = 2
auto_shutdown = true
log_type = "tensorboard"
log_prefix = ""
log_dir = "./logs"
log_tracker_name = ""
offload_inactive_dit = false
mixed_precision = "bf16"
