dataset_config = "E:\\train\\tiquhuawen\\tiquhuawen.toml"
vae_path = "I:\\train_models\\kontext\\ae.safetensors"
t5_path = "I:\\train_models\\kontext\\t5xxl_fp16.safetensors"
clip_model_path = "I:\\train_models\\kontext\\clip_l.safetensors"
dit_weights_path = "I:\\train_models\\kontext\\flux1-kontext-dev.safetensors"
batch_size = "16"
max_train_epochs = "200"
learning_rate = "2e-4"
network_dim = "32"
gradient_accumulation_steps = "1"
timestep_sampling = "flux_shift"
enable_low_vram = true
blocks_to_swap = "20"
output_dir = "./output"
output_name = "tiquhuawen"
save_every_n_epochs = "1"
save_every_n_steps = "1000"
use_network_weights = false
network_weights_path = "D:\\work\\project\\LoRAMaster\\LoRAMaster\\output\\wan2.2_jerry3d_t2v.safetensors"
generate_samples = true
sample_every_n_epochs = "1000"
sample_every_n_steps = "100"
sample_prompt_text = "Extract the fabric print. Delete folds, buttons, seams, and shadows.print smooth spread across the entire canvas."
sample_image_path = "E:\\train\\tiquhuawen\\controls\\1.png"
sample_w = "512"
sample_h = "512"
sample_seed = "666666"
sample_steps = "10"
sample_at_first = false
custom_prompt_txt = false
custom_prompt_path = ""
num_cpu_threads_per_process = 1
num_processes = 1
lazy_loading = false
attention_implementation = "sdpa"
optimizer_type = "adamw8bit"
max_data_loader_n_workers = 2
auto_shutdown = true
log_type = "tensorboard"
log_prefix = ""
log_dir = "./logs"
log_tracker_name = ""
offload_inactive_dit = false
mixed_precision = "bf16"
lr_scheduler = "constant"
lr_warmup_steps = "0"
lr_scheduler_num_cycles = "1"
custom_params = ""
