edit = true
dataset_config = "E:\\train\\tiquhuawen\\qwen_image_edit_tiquhuawen.toml"
vae_path = "I:\\train_models\\qwen_image\\qwen_image_vae.safetensors"
text_encoder_model_path = "I:\\train_models\\qwen_image\\qwen_2.5_vl_7b.safetensors"
dit_weights_path = "I:\\train_models\\qwen_image\\qwen_image_edit_bf16.safetensors"
batch_size = "1"
max_train_epochs = "200"
learning_rate = "5e-5"
network_dim = "32"
gradient_accumulation_steps = "1"
timestep_sampling = "shift"
discrete_flow_shift = "2.2"
enable_low_vram = true
blocks_to_swap = "20"
output_dir = "./output"
output_name = "qwen_image_edit_qiquhuawen"
save_every_n_epochs = "1"
save_every_n_steps = "500"
generate_samples = false
sample_every_n_epochs = "1000"
sample_every_n_steps = "1000"
sample_prompt_text = "Ultra HD 8K, aiblender,hyper-detailed 3D render of a cheerful character smiling warmly and waving both hands in a friendly greeting. The motion is fluid and energetic, with subtle motion blur emphasizing the dynamic gesture. Soft volumetric lighting illuminates the scene, creating a heartwarming atmosphere. The background features a beautifully blurred bokeh effect with golden sunlight, adding depth and cinematic quality. Rendered in Unreal Engine 5, Pixar-style animation, ultra-realistic textures, and vibrant colors. Trending on ArtStation, award-winning digital art, 16K resolution."
sample_image_path = "E:\\portables\\ComfyUI_Wan\\ComfyUI\\input\\pasted\\baozha_test.png"
sample_w = "512"
sample_h = "512"
sample_frames = "33"
sample_seed = "666666"
sample_steps = "10"
sample_at_first = false
custom_prompt_txt = false
custom_prompt_path = ""
fp8 = true
num_cpu_threads_per_process = 1
num_processes = 1
attention_implementation = "sdpa"
optimizer_type = "adamw8bit"
max_data_loader_n_workers = 2
auto_shutdown = true
log_type = "tensorboard"
log_prefix = ""
log_dir = "./logs"
log_tracker_name = ""
offload_inactive_dit = false
mixed_precision = "bf16"
