edit = false
dataset_config = "E:\\train\\fenggelora\\jblfg_v2\\jblfg_qwen.toml"
vae_path = "I:\\train_models\\qwen_image\\qwen_image_vae.safetensors"
text_encoder_model_path = "I:\\train_models\\qwen_image\\qwen_2.5_vl_7b.safetensors"
dit_weights_path = "I:\\train_models\\qwen_image\\qwen_image_bf16.safetensors"
batch_size = "1"
max_train_epochs = "200"
learning_rate = "1e-5"
network_dim = "64"
gradient_accumulation_steps = "1"
timestep_sampling = "shift"
discrete_flow_shift = "2.2"
enable_low_vram = true
blocks_to_swap = "20"
output_dir = "./output"
output_name = "jblfg_qwen_v2"
save_every_n_epochs = "10"
save_every_n_steps = "500"
generate_samples = true
sample_every_n_epochs = "1"
sample_every_n_steps = "100"
sample_prompt_text = "jblfg, masterpiece, best quality, 1girl, in white shirts, full body, looking at viewer, simple background, blue sky"
sample_image_path = "E:\\train\\tiquhuawen\\controls\\1.png"
sample_w = "512"
sample_h = "512"
sample_seed = "666666"
sample_steps = "10"
sample_at_first = false
custom_prompt_txt = false
custom_prompt_path = ""
fp8 = true
num_cpu_threads_per_process = 1
num_processes = "100"
attention_implementation = "sdpa"
optimizer_type = "adamw8bit"
max_data_loader_n_workers = 2
auto_shutdown = true
log_type = "tensorboard"
log_prefix = ""
log_dir = "./logs"
log_tracker_name = ""
offload_inactive_dit = false
mixed_precision = "bf16"
lr_scheduler = "constant"
lr_warmup_steps = "0"
lr_scheduler_num_cycles = "1"
custom_params = ""
