train_type = "qwen_image_edit_plus"
edit = true
dataset_config = "E:\\train\\qwen_edit_plus\\fangxiangpan\\fangxiangpan.toml"
vae_path = "I:\\train_models\\qwen_image\\qwen_image_vae.safetensors"
text_encoder_model_path = "I:\\train_models\\qwen_image\\qwen_2.5_vl_7b.safetensors"
dit_weights_path = "I:\\train_models\\qwen_image\\qwen_image_edit_2509_bf16.safetensors"
batch_size = "1"
max_train_epochs = "200"
learning_rate = "5e-5"
network_dim = "32"
gradient_accumulation_steps = "1"
timestep_sampling = "shift"
discrete_flow_shift = "2.2"
enable_low_vram = true
blocks_to_swap = "50"
output_dir = "./output"
output_name = "fangxianpan_v1"
save_every_n_epochs = "10"
save_every_n_steps = "500"
generate_samples = false
sample_every_n_epochs = "1"
sample_every_n_steps = "100"
sample_prompt_text = "A beautiful girl sitting on the grass in a meadow, long hair flowing in the breeze, soft sunlight, warm and peaceful atmosphere, highly detailed, cinematic, frxxz_style"
sample_image_path = "E:\\train\\tiquhuawen\\controls\\1.png"
sample_w = "512"
sample_h = "512"
sample_seed = "666666"
sample_steps = "10"
sample_at_first = false
custom_prompt_txt = false
custom_prompt_path = ""
fp8 = true
num_cpu_threads_per_process = 1
num_processes = "100"
attention_implementation = "sdpa"
optimizer_type = "adamw8bit"
max_data_loader_n_workers = 2
auto_shutdown = true
log_type = "tensorboard"
log_prefix = ""
log_dir = "./logs"
log_tracker_name = ""
offload_inactive_dit = false
mixed_precision = "bf16"
lr_scheduler = "constant"
lr_warmup_steps = "0"
lr_scheduler_num_cycles = "1"
custom_params = ""
use_network_weights = false
network_weights_path = "D:\\work\\project\\LoRAMaster\\LoRAMaster\\output\\tiquhuawen_v7-step00004000.safetensors"
