dataset_path = "E:\\train\\fenggelora\\jblfg_test\\images"
caption_type = "Stable Diffusion Prompt"
caption_length = "30"
temperature = "0.6"
top_p = "0.9"
top_k = "0"
max_new_tokens = 741
trigger_word = "jblfg,"
filter_word = ""
refer_character_name = false
exclude_people_info = false
include_lighting = false
include_camera_angle = false
include_watermark = false
include_JPEG_artifacts = false
include_exif = false
exclude_sexual = false
exclude_image_resolution = false
include_aesthetic_quality = false
include_composition_style = false
exclude_text = false
specify_depth_field = false
specify_lighting_sources = false
do_not_use_ambiguous_language = false
include_nsfw = false
only_describe_most_important_elements = false
do_not_include_artist_name_or_title = false
identify_image_orientation = false
use_vulgar_slang_and_profanity = false
do_not_use_polite_euphemisms = false
include_character_age = false
include_camera_shot_type = false
exclude_mood_feeling = false
include_camera_vantage_height = false
mention_watermark = false
avoid_meta_descriptive_phrases = false
fp8 = true
